-- create table customer
CREATE TABLE `customer` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(255) DEFAULT NULL,
  `CONTACT` varchar(255) DEFAULT NULL,
  `TELEPHONE` varchar(255) DEFAULT NULL,
  `EMAIL` varchar(255) DEFAULT NULL,
  `REMARK` text,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=124 DEFAULT CHARSET=utf8;

INSERT INTO CUSTOMER (NAME, CONTACT, TELEPHONE, EMAIL, REMARK)
VALUES ("NAME0", "CONTACT0","TELEPHONE0", "EMAIL0", "REMARK0"),
("NAME1", "CONTACT1","TELEPHONE1", "EMAIL1", "REMARK1"),
("NAME2", "CONTACT2","TELEPHONE2", "EMAIL2", "REMARK2");
